trigger: none

pool:
 name: TF

stages:
  -  stage: Deploy
     jobs:
       -  deployment: Test
          environment: Test
          strategy: 
           runOnce:
             deploy:
                steps:
                  - checkout: self
                  - script: echo " First deployment Job demo"
