trigger:
- main

pool:
 name: TF

stages:
  - stage: Dev
    jobs:
      - job: JobA
        steps:
          - script: echo " im kishore"

  - stage: Test
    jobs:
      - job: JobB
        steps:
          - script: echo "kishore"

      - job: JobC
      - job: jobD

          