pool:
 name: TF

stages:
  - stage: QA
    jobs:
      - job: QAjob

  - stage: prod
    jobs:  
      - job: prodjob

  - stage: Test
    dependsOn: QA
    jobs:
      - job: Testjob


         

          