trigger:
- master

pool:
  name: 'TF'
stages:
  - stage: A
    jobs:
      - job: jobA
        steps:
          - script: echo "iam kishore"
  - stage: B
    jobs:
      - job: JobB
        steps:
          - script: echo "hi"
