trigger:
- master

pool:
  name: 'TF'
stages:
  - stage: Test
    jobs:
      - job: Name
        steps:
          - script: echo "iam kishore"
  - stage: Dev
    jobs:
      - job: Hi
        steps:
          - script: echo "hi"
