pool:
 name: TF

stages:
  - stage: Test
    jobs:
      - job: TestJob
  - stage: Dev
    dependsOn: Prod
    jobs:  
      - job: DevJOb

  - stage: Prod
    jobs:
      - job: PordJob


         

          